name: Run AbuseIPDB Script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up API key
        run: echo "ABUSEIPDB_API_KEY=${{ secrets.ABUSEIPDB_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq curl

      - name: Run the script
        run: bash your-script.sh  # Replace with the name of your script
        env:
          ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
